//! Golden-file tests: `foldback analyze <fixture>` against checked-in
//! fixture session files, asserting exact text output. Fixtures are
//! generated by `examples/gen_fixtures.rs` and checked into
//! `tests/fixtures/` — regenerate deliberately, not automatically, when
//! the report format changes, and review the resulting diff.
//!
//! Also covers the `ci-check` exit-code contract per
//! foldback-testing-plan.md §2: "0 on clean session, non-zero on
//! divergence... a silent behavior change here breaks every CI pipeline
//! using it."

use assert_cmd::Command;
use predicates::prelude::*;

fn fixture(name: &str) -> String {
    format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn analyze_clean_fixture_exact_output() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["analyze", &fixture("clean.foldback")])
        .assert()
        .success()
        .stdout(predicate::eq(
            "format_version : 1\n\
             tick_rate_hz   : 60\n\
             peer_count     : 2\n\
             build_id       : 00000000000000000000000000000000\n\
             ended cleanly  : true\n\
             \n\
             tick hashes    : 20\n\
             entity hashes  : 0\n\
             field hashes   : 0\n\
             snapshots      : 0\n\
             metadata       : 0\n\
             \n\
             divergence     : none found\n",
        ));
}

#[test]
fn analyze_diverging_fixture_exact_output() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["analyze", &fixture("diverging.foldback")])
        .assert()
        .success()
        .stdout(predicate::eq(
            "format_version : 1\n\
             tick_rate_hz   : 60\n\
             peer_count     : 2\n\
             build_id       : 00000000000000000000000000000000\n\
             ended cleanly  : true\n\
             \n\
             tick hashes    : 20\n\
             entity hashes  : 0\n\
             field hashes   : 0\n\
             snapshots      : 0\n\
             metadata       : 0\n\
             \n\
             divergence     : tick 6\n",
        ));
}

#[test]
fn analyze_truncated_fixture_recovers_complete_frames() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["analyze", &fixture("truncated.foldback")])
        .assert()
        .success()
        .stdout(
            predicate::str::contains("ended cleanly  : false")
                .and(predicate::str::contains("tick hashes    : 4")),
        );
}

#[test]
fn ci_check_exit_code_zero_on_clean() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["ci-check", &fixture("clean.foldback")])
        .assert()
        .success()
        .stdout(predicate::str::contains("clean: no divergence"));
}

#[test]
fn ci_check_exit_code_nonzero_on_divergence() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["ci-check", &fixture("diverging.foldback")])
        .assert()
        .code(1)
        .stderr(predicate::str::contains("DIVERGENCE DETECTED at tick 6"));
}

#[test]
fn analyze_missing_file_clear_error_no_panic() {
    Command::cargo_bin("foldback")
        .unwrap()
        .args(["analyze", "/nonexistent/path/does-not-exist.foldback"])
        .assert()
        .failure()
        .code(2)
        .stderr(predicate::str::contains("could not open"));
}

#[test]
fn analyze_malformed_file_clear_error_no_panic() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("garbage.foldback");
    std::fs::write(
        &path,
        b"this is not a foldback file at all, just garbage bytes",
    )
    .unwrap();

    Command::cargo_bin("foldback")
        .unwrap()
        .args(["analyze", path.to_str().unwrap()])
        .assert()
        .failure()
        .code(2)
        .stderr(predicate::str::contains("magic"));
}

#[test]
fn analyze_missing_argument_conflicting_flags() {
    Command::cargo_bin("foldback")
        .unwrap()
        .arg("analyze")
        .assert()
        .failure();
}
