// SPDX-License-Identifier: MIT OR Apache-2.0
#include "FoldbackSession.h"

// foldback.h is generated by cbindgen with `language = "C"` and
// `cpp_compat = true` — the latter added by this binding (Unity/Godot
// never needed it: C# P/Invoke and gdext never compile this header at
// all), which makes cbindgen emit its own `#ifdef __cplusplus extern "C"`
// guard and avoid a real enum/typedef redefinition error C++ hits that C
// doesn't. See cbindgen.toml's comment for the full story.
#include "foldback.h"

FFoldbackSession::~FFoldbackSession()
{
	if (Handle)
	{
		foldback_session_destroy(Handle);
		Handle = nullptr;
	}
}

FFoldbackSession::FFoldbackSession(FFoldbackSession&& Other) noexcept
	: Handle(Other.Handle)
	, LastError(MoveTemp(Other.LastError))
{
	Other.Handle = nullptr;
}

FFoldbackSession& FFoldbackSession::operator=(FFoldbackSession&& Other) noexcept
{
	if (this != &Other)
	{
		if (Handle)
		{
			foldback_session_destroy(Handle);
		}
		Handle = Other.Handle;
		LastError = MoveTemp(Other.LastError);
		Other.Handle = nullptr;
	}
	return *this;
}

void FFoldbackSession::SetLastErrorFromNative()
{
	const uintptr_t NeededLen = foldback_last_error(nullptr, 0);
	if (NeededLen == 0)
	{
		LastError.Empty();
		return;
	}
	TArray<char> Buf;
	Buf.SetNumUninitialized(static_cast<int32>(NeededLen) + 1);
	foldback_last_error(Buf.GetData(), Buf.Num());
	LastError = UTF8_TO_TCHAR(Buf.GetData());
}

bool FFoldbackSession::Configure(const FConfig& Config)
{
	if (Handle)
	{
		foldback_session_destroy(Handle);
		Handle = nullptr;
	}

	FoldbackConfig NativeConfig{};
	NativeConfig.tick_rate_hz = Config.TickRateHz;
	NativeConfig.peer_count = Config.PeerCount;
	NativeConfig.local_peer_id = Config.LocalPeerId;
	NativeConfig.retention = Config.Retention;
	FMemory::Memzero(NativeConfig.build_id);

	const FTCHARToUTF8 PathUtf8(*Config.RecordToPath);
	NativeConfig.record_to_path = Config.RecordToPath.IsEmpty() ? nullptr : PathUtf8.Get();

	Handle = foldback_session_create(&NativeConfig);
	if (!Handle)
	{
		SetLastErrorFromNative();
		return false;
	}
	LastError.Empty();
	return true;
}

bool FFoldbackSession::HashTick(uint64 Tick, TArrayView<const uint8> State)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FoldbackStatus Status = foldback_hash_tick(Handle, Tick, State.GetData(), State.Num());
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

bool FFoldbackSession::RecordPeerHash(uint64 Tick, uint16 PeerId, uint64 Hash)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FoldbackStatus Status = foldback_record_peer_hash(Handle, Tick, PeerId, Hash);
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

bool FFoldbackSession::HashEntity(uint64 Tick, uint64 EntityId, TArrayView<const uint8> State)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FoldbackStatus Status = foldback_hash_entity(Handle, Tick, EntityId, State.GetData(), State.Num());
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

bool FFoldbackSession::RecordPeerEntityHash(uint64 Tick, uint16 PeerId, uint64 EntityId, uint64 Hash)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FoldbackStatus Status = foldback_record_peer_entity_hash(Handle, Tick, PeerId, EntityId, Hash);
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

bool FFoldbackSession::HashField(uint64 Tick, uint64 EntityId, const FString& FieldName, TArrayView<const uint8> Value)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FTCHARToUTF8 FieldNameUtf8(*FieldName);
	const FoldbackStatus Status =
		foldback_hash_field(Handle, Tick, EntityId, FieldNameUtf8.Get(), Value.GetData(), Value.Num());
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

bool FFoldbackSession::RecordPeerFieldHash(uint64 Tick, uint16 PeerId, uint64 EntityId, const FString& FieldName,
	uint64 Hash, TArrayView<const uint8> Value)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FTCHARToUTF8 FieldNameUtf8(*FieldName);
	const FoldbackStatus Status = foldback_record_peer_field_hash(
		Handle, Tick, PeerId, EntityId, FieldNameUtf8.Get(), Hash, Value.GetData(), Value.Num());
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

uint64 FFoldbackSession::PendingHashCount() const
{
	return Handle ? foldback_pending_hash_count(Handle) : 0;
}

TArray<TPair<uint64, uint64>> FFoldbackSession::TakePendingHashes(uint64 Max)
{
	TArray<TPair<uint64, uint64>> Out;
	if (!Handle || Max == 0)
	{
		return Out;
	}
	TArray<FoldbackPendingHash> Native;
	Native.SetNumUninitialized(static_cast<int32>(Max));
	const uintptr_t Drained = foldback_take_pending_hashes(Handle, Native.GetData(), Native.Num());
	Out.Reserve(static_cast<int32>(Drained));
	for (uintptr_t i = 0; i < Drained; ++i)
	{
		Out.Emplace(Native[i].tick, Native[i].hash);
	}
	return Out;
}

bool FFoldbackSession::CheckDivergence(uint64& OutTick)
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	bool bFound = false;
	uint64 Tick = 0;
	const FoldbackStatus Status = foldback_check_divergence(Handle, &bFound, &Tick);
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	if (bFound)
	{
		OutTick = Tick;
	}
	return bFound;
}

uint64 FFoldbackSession::Finish() const
{
	return Handle ? foldback_finish(Handle) : 0;
}

bool FFoldbackSession::FinishRecording()
{
	if (!Handle)
	{
		LastError = TEXT("session not configured — call Configure() first");
		return false;
	}
	const FoldbackStatus Status = foldback_finish_recording(Handle);
	if (Status != Ok)
	{
		SetLastErrorFromNative();
		return false;
	}
	return true;
}

uint32 FFoldbackSession::TickRateHz() const
{
	return Handle ? foldback_tick_rate_hz(Handle) : 0;
}

uint32 FFoldbackSession::PeerCount() const
{
	return Handle ? foldback_peer_count(Handle) : 0;
}
